- name: Install and start docker engine
  hosts: postgres
  become: true
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Uninstall older version of docker
      yum:
        name: '{{ item }}'
        state: removed
      with_items:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine

    - name: Install yum utils
      yum:
        name:
          - yum-utils
          - amazon-linux-extras
          - device-mapper-persistent-data
          - lvm2
        state: latest

    - name: Install docker
      shell: amazon-linux-extras install docker -y

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Start the docker
      systemd:
        name: docker
        enabled: yes
        state: started
    # Necessary when running ansible on the remote control system. In my case i installed locally via pip
    # - name: Install the PIP
    #   package:
    #     name: python3-pip
    #     state: present
    # - name: Install docker sdk to manager stuff
    #   pip:
    #     name: docker

- name: Copy project files and start container
  hosts: postgres
  become: yes
  tasks:
    - name: Create project directory
      file:
        path: /home/ec2-user/postgres
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy postgres folder recursively
      copy:
        src: /mnt/c/ansible-web-app-project-ec2/todo-app-pern/database/
        dest: /home/ec2-user/postgres

    - name: remove container and image if exist
      shell: "docker ps -q --filter 'name=postgres' && docker stop postgres && docker rm -fv postgres && docker image rm -f ibrarmunir009/postgres || echo 'Not Found'"

    - name: build docker image
      docker_image:
        name: ibrarmunir009/postgres
        build:
          path: /home/ec2-user/postgres
        source: build
        state: present

    - name: create postgresql docker container
      docker_container:
        name: postgres
        image: ibrarmunir009/postgres
        state: started
        ports:
          - '5432:5432'
        env:
          POSTGRES_PASSWORD: ibrar123
        volumes:
          - /db-data:/var/lib/postgresql/data
      register: container_info

    - name: print the container info
      debug:
        var: container_info
