- name: Install and start docker engine
  hosts: react
  become: true
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: Uninstall older version of docker
      yum:
        name: '{{ item }}'
        state: removed
      with_items:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
    - name: Install yum utils
      yum:
        name:
          - yum-utils
          - amazon-linux-extras
          - device-mapper-persistent-data
          - lvm2
        state: latest
    - name: Install docker
      shell: amazon-linux-extras install docker -y
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Start the docker
      systemd:
        name: docker
        enabled: yes
        state: started

- name: Copy project files and start container
  hosts: react
  become: yes
  tasks:
    - name: Create project directory
      file:
        path: /home/ec2-user/react
        state: directory
        owner: root
        group: root
        mode: '0744'

    - name: Copy cient folder recursively
      copy:
        src: /mnt/c/ansible-web-app-project-ec2/todo-app-pern/client/
        dest: /home/ec2-user/react

    - name: remove container and image if exist
      shell: "docker ps -q --filter 'name=client' && docker stop client && docker rm -fv client && docker image rm -f ibrarmunir009/client || echo 'Not Found'"

    - name: build docker image
      docker_image:
        name: ibrarmunir009/client
        build:
          path: /home/ec2-user/react
        source: build
        state: present

    - name: create client container
      docker_container:
        name: client
        image: ibrarmunir009/client
        state: started
        ports:
          - '3000:3000'
      register: container_info

    - name: print the container info
      debug:
        var: container_info
